### ISSUE TITLE
[New Feature] More Foundation Size Options

### ISSUE THREAD

**Issue by XNiPERIANZ** [Vinifera-Developers/Vinifera#1006]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, videos, links, etc)*.

### Description

Giving mod creator to have more option for building design and size, with 7x7 as the maximal foundation size.

curently the only available building foundation size : 

1x1
1x2
1x3
2x1
2x2
2x3
3x1
3x2
3x3
3x4
3x5
4x2
4x3
4x4
5x3
6x4

### Proposed Code (optional)

1x1 up to 1x7
2x1 up to 2x7
3x1 up to 3x7
4x1 up to 4x7
5x1 up to 5x7
6x1 up tp 6x7
7x1 up to 7x7

**Comment by CCHyper** [comment]
@XNiPERIANZ, we have a feature request for this that is currently open _(see Issue #104)_.

Closing this in favor of #104.
