### ISSUE TITLE
[New Feature] Commander / Hero unit marker

### ISSUE THREAD

**Issue by XNiPERIANZ** [Vinifera-Developers/Vinifera#1009]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, videos, links, etc)*.

### Description

 giving specific mark for special unit in TS like Commander/Hero/SPY/Agent unit without need to selected via cursor ( it should work like unit Veterancy ), by using CommanderUnit=yes & SpyUnit=yes Tag

### Proposed Code (optional)

Rules.ini

[General]
CommanderLabel= *this will refer to art.ini*
Spy or AgentLabel= *this will refer to art.ini*

[Unit]
CommanderUnit=yes/true
SpyUnit=yes/true

Art.ini
[Marker]
Xpos=(num)
Ypos=(num)

### Additional Context

![veterancy](https://user-images.githubusercontent.com/112654985/231121668-9584e906-8ffb-4351-9be3-fdb4f6497c4c.PNG)

**Comment by ZivDero** [comment]
Possible since 9a15a50a0bb349151684b05a35913d905768415f
