### ISSUE TITLE
[Vanilla Bug] Unused and unsupported SuperWeapon animations

### ISSUE THREAD

**Issue by Crimsonum** [Vinifera-Developers/Vinifera#101]
### Description:
The Nod Missile Silo building has an unused animation for opening the missile hatches (NAMISL_A). This animation, and its damaged counterpart (NAMISL_AD) were supposed to play when any of the superweapon missiles are launched from the building. Similarly, the GDI Firestorm Generator has an unused animation where the "lid" rises up and the generator activates (GAFIRE_A). However, the game apparently lacks the code necessary to play these animations at the right time, thus they're never seen in-game.

For reference, Tiberian Dawn and Red Alert both have functional building animations when a nuclear missile is launched from a Temple of Nod/Missile Silo. Red Alert 2 added support for animations depicting superweapon buildings at different states (idle, powering up, activated, powering down).

### Steps To Reproduce:
1. Build a Nod Missile Silo and launch a Multi-Missile or Chemical Missile.
2. Build a GDI Firestorm Generator and activate the Firestorm Defense.

### Expected Behaviour:
1. When a missile superweapon is activated, the silo door would open and the missile would fly out. The silo door would then close.
2. When the Firestorm Defense is activated, the generator lid would rise up and the generator would activate. Once the charge runs out or the building runs out of power, the generator deactivates and the lid closes (the lid animation would play in reverse).

### Actual Behaviour:
1. No silo door animation is played.
2. No animation for opening the lid is played, and the active generator animation is played as a regular building animation (i.e. regardless whether the superweapon is activated or not).

**Comment by CCHyper** [comment]
Does the game already have INI keys and associated logics to handle these on other types of buildings? Or would this need to be coupled with a new feature request?

**Comment by Crimsonum** [comment]
> Does the game already have INI keys and associated logics to handle these on other types of buildings? Or would this need to be coupled with a new feature request?

I would assume there's some code left from TD/RA that changes the building art when a superweapon is activated, but I'm not sure. There are no INI controls for this, at least.

**Comment by CCHyper** [comment]
I suppose we could fix this by making sure only Missile Silo's buildings with `NukeSilo=yes` use this new animation sequence, this would make sure the original game works as intended without needing any new INI keys.

But I'm not aware of such an INI key for the Firestorm Generator?

**Comment by Crimsonum** [comment]
> But I'm not aware of such an INI key for the Firestorm Generator?

The building has no special key, but there's the `[General] -> GDIFirestormGenerator=` key that could potentially be used.

**Comment by CCHyper** [comment]
> The building has no special key, but there's the `[General] -> GDIFirestormGenerator=` key that could potentially be used.
I feel this is too far detached from the BuildingType, and although it fixes the bug on the surface level, might open it up to a new edge case bug creeping in.

Some research would need to be done to find the best solution for this.

**Comment by Crimsonum** [comment]
> I know that DTA's missile silos have an opening animation that plays during the launch sequence, if that helps at all.

I haven't looked at DTA's code for the nuke in particular, but if I had to guess, it's probably done as an animation attached to the nuke missile weapon. TI does this too. It works, but it has its drawbacks, like no damaged version of the animation.
