### ISSUE TITLE
[Vanilla Bug] Harvesters prefer far away refineries on large maps

### ISSUE THREAD

**Issue by Bittah** [Vinifera-Developers/Vinifera#1025]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, debug and exception logs, etc)*.

### Description

When you own refineries on opposite sides of a large map, harvesters will consistently move to the other side of the map to unload and back again, even when the refinery on the other side of the map is already occupied and the nearby one is free.

### Steps To Reproduce

Vanilla TS:
1. Extract [sbr.mpr](https://github.com/Vinifera-Developers/Vinifera/files/12071745/VanillaTS.zip) into vanilla TS game directory.
2. Select the custom map (Super Bridgehead Redux; it should be at the bottom and have no preview image), select GDI and Gold and start the match.
3. Use the pre-placed Engineers to capture the refineries in the upper right and bottom left corners of the map.
4. Order the harvesters to start harvesting.

TS Client:
1. Extract [sbr.map](https://github.com/Vinifera-Developers/Vinifera/files/12071759/TSClient.zip) into the `\Maps\Custom` folder.
2. Select starting location 1 and start the match.

### Expected Behaviour

The harvesters dock at the nearest refinery once they're full.

### Actual Behaviour

The harvesters move to the refinery at the other side of the map to dock and then move back to the other side of the map to harvest again.

**Comment by Rampastring** [comment]
Fixed in https://github.com/Vinifera-Developers/Vinifera/commit/23ecaec05d6f928588547b99c5acf6791957b242
