### ISSUE TITLE
[Vanilla Bug] Sensors=yes doesn't do anything

### ISSUE THREAD

**Issue by Paladin-Bloodmoon** [Vinifera-Developers/Vinifera#1043]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, debug and exception logs, etc)*.

### Description

before I get started, this might be a vinifera bug, but I don't recall the tag doing anything without vinifera either, so correct me if I'm wrong

the rules.ini tag "Sensors=yes" doesn't actually do anything that you'd think a unit with sensors would do, you get no stealth detection.

### Required Code (optional)

Sensors=yes would probably need to used in conjunction with a new tag so you can customize stealth detection radius too, tag would be "SensorRadius=<integer>"

### Steps To Reproduce

put Sensors=yes on literally any unit, move to a cloaked unit

### Expected Behaviour

should reveal the cloaked unit the same way the mobile sensor array does

### Actual Behaviour

doesn't do jackshit

**Comment by Crimsonum** [comment]
Sensors works in vanilla TS and I'm not aware of any patch breaking it. What it does is it fully reveals any immediately adjacent cloaked object same way infantry would.

**Comment by ZivDero** [comment]
Not a bug.
[Sensors](https://modenc.renegadeprojects.com/Sensors)
