### ISSUE TITLE
[Vinifera Bug] active electric bolts crashing game while load/save or quit the game

### ISSUE THREAD

**Issue by MarkJFox** [Vinifera-Developers/Vinifera#1051]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, debug and exception logs, etc)*.

### Description

In https://github.com/Vinifera-Developers/Vinifera/pull/545 electric bolts like the Red Alert 2 Tesla Zapps got added. Adding the values to a weapon with the 'Invisible' projectile works without any issues, except you are trying to load a saved game, create a new save game or quiting the game (via ALF + F4 or "Abort Mission") causing a game crash while the electic bolt is active. 

### Required Code (optional)

I used that WH for my cheat unit for testing

[CheatTesla]
Bright=yes
Damage=2500
ROF=120
Range=10.5
Speed=100
Warhead=RailShot
;Report=OBELRAY1
Projectile=Invisible ;only Invisible works
Charges=no
IsElectricBolt=yes
EBoltColor1=255,255,255 ;<r,g,b> Defaults to 255,255,255.
EBoltColor2=0,255,0; 82,81,255   ;<r,g,b> Defaults to 82,81,255.
EBoltColor3=82,81,255   ;<r,g,b> Defaults to 82,81,255.
EBoltSegmentCount=8 ; Default is 8
EBoltLifetime=1700 ; in frames - Default is 17
EBoltIterations=1 ; how many bolts - 1 Iteration are 3 bolts - Default is 1
EBoltDeviation=1.0 ; Default is 1.0

### Steps To Reproduce

- Create or modify a WH and add the electic bolt values from the link above and add that weapon to an unit. Make sure to use the Invisible Projectile
- Fire the weapon ingame
- Try to save/load a game or quit the game while the electric bolt animation is active (doesn't care if visible on screen or not)

### Expected Behaviour

Load / save a game or quit the game while the bold is active should work as expected, without any crashes.

### Actual Behaviour

The game crashes.

### Version

nightly 44bec0b

### Additional Context

[DEBUG_31-03-2024_17-33-15.LOG](https://github.com/Vinifera-Developers/Vinifera/files/14816568/DEBUG_31-03-2024_17-33-15.LOG)
[EXCEPT_31-03-2024_17-33-15.TXT](https://github.com/Vinifera-Developers/Vinifera/files/14816569/EXCEPT_31-03-2024_17-33-15.TXT)

**Comment by ZivDero** [comment]
Fixed in #45fb6d
