### ISSUE TITLE
[Vinifera Bug] Loading a game from 'Mission Failed' dialog doesn't work

### ISSUE THREAD

**Issue by MarkJFox** [Vinifera-Developers/Vinifera#1053]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, debug and exception logs, etc)*.

### Description

If you get a 'Mission failed', the game shows up that message:
![Screenshot 2024-03-31 200439](https://github.com/Vinifera-Developers/Vinifera/assets/127884235/727e149f-5742-4297-bf06-c5da2c865868)
After a click of 'Load game' the following message appears:
![Screenshot 2024-03-31 200503](https://github.com/Vinifera-Developers/Vinifera/assets/127884235/0376b1e3-6e83-4ce0-b253-4b61efa74053)

But it is possible to save and load games in the nightly, so this message box must be a left over from earlier days.

### Steps To Reproduce

Fail a mission and click on the 'Load game' button

### Expected Behaviour

The game should show the 'Load Game' Dialog where the player can select and load a save game.

### Actual Behaviour

The game shows the 'save/load a game is disabled' dialog

### Version

nightly 44bec0b

**Comment by ZivDero** [comment]
Resolved in 9a15a50a0bb349151684b05a35913d905768415f
