### ISSUE TITLE
[Vinifera Bug] Building graphics glitch out when built while under attack

### ISSUE THREAD

**Issue by Crimsonum** [Vinifera-Developers/Vinifera#1074]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, debug and exception logs, etc)*.

### Description

When a building with a weapon is built or deployed, if it's simultaneously under enemy attack, its buildup animation and the building shape will glitch out. The body of the building disappears, and the shadow of the building (if any) is drawn as if it were a normal, opaque frame. See the attached example.

### Steps To Reproduce

For example: Attack an enemy tick tank with vehicles (infantry will not trigger the tank to deploy) or have the enemy attack your tick tanks as you deploy them.

Alternatively, attack a defense building as it's being deployed.

### Expected Behaviour

The buildings deploy as normal, no glitches.

### Actual Behaviour

The buildup anim and building frames are glitched out.

### Version

edd3322

### Additional Context

![untitled](https://github.com/user-attachments/assets/9b78e1f8-453b-43a1-8163-ca2c31f495e6)

**Comment by Rampastring** [comment]
This also happens sometimes when a new building is constructed and the building is attacked during its buildup anim.

**Comment by Crimsonum** [comment]
Updated the title and description.

**Comment by ZivDero** [comment]
Fixed in fa89d879187d3a3156e287d65976dec1dea54cc6
