### ISSUE TITLE
[Vinifera Bug] PipScale=Charge ignores MaxPips

### ISSUE THREAD

**Issue by Crimsonum** [Vinifera-Developers/Vinifera#1098]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, debug and exception logs, etc)*.

### Description

As the title says. Units with `PipScale=Charge` should have 8 pips by default. It is now set to 5. Changing this in `[AudioVisual] -> MaxPips=` has no effect.

### Required Code (optional)

For example:
```ini
[AudioVisual]
MaxPips=5,5,10,10,8 ;last value is for Charge, i.e. 8 pips
```

### Steps To Reproduce

1. Build a Mobile EM Pulse (MOBILEMP)

### Expected Behaviour

The Mobile EMP's charge meter should have 8 pips.

### Actual Behaviour

The Mobile EMP's charge meter has only 5 pips.

### Version

223c1fb

### Additional Context

![example](https://github.com/user-attachments/assets/6958ca1f-f3f5-4440-8991-064bdbc9284c)

**Comment by ZivDero** [comment]
Fixed in c83e063c2a5c61ae600dd297904560782e323fb4
