### ISSUE TITLE
[Vanilla Bug] Animations with `RandomLoopDelay` use the unsynchronized RNG

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#114]
### Description:
Animations that use `RandomLoopDelay` use the unsynchronized random-number generator to generate their loop delay. This causes such animations to cause sync errors in multiplayer. Animations that use `RandomLoopDelay` should use the synchronized RNG instead.

### Additional Files:
CnCNet ts-patches has a fix for this: https://github.com/CnCNet/ts-patches/blob/master/src/random_loop_delay.asm

**Comment by CCHyper** [comment]
While I do see this as a valid bug fix, I noticed some of the Tiberian Sun animations actually use `RandomLoopDelay`, does this issue not appear in standard/unmodded Tiberian Sun and this issue appears when modding the game?
