### ISSUE TITLE
[Vanilla Bug] Don't respawn pre-placed crates when crates are disabled

### ISSUE THREAD

**Issue by Bittah** [Vinifera-Developers/Vinifera#1141]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, videos, links, etc)*.

### Description

Pre-placed crates and crates spawned from destroyed trucks re-spawn in multiplayer when they are picked up, even if the Crates setting is disabled.

Ideally these pre-placed/truck crates also shouldn't respawn when crates _are_ enabled so that the total number of respawning crates on the map won't increase.

### Additional Context

Implemented in ts-patches: https://github.com/CnCNet/ts-patches/blob/master/src/no_crate_respawn_with_crates_disabled.asm

**Comment by ZivDero** [comment]
Fixed in [#380](https://github.com/Vinifera-Developers/Vinifera/pull/380)
