### ISSUE TITLE
[New Feature] Allow defining tutorial lines in map files

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#123]
### Description:
Vanilla TS allows defining tutorial / text trigger lines in `Tutorial.ini` only. This is bad for custom maps, as they cannot create their own tutorial lines.

### Additional Files:
CnCNet ts-patches has a hack that makes the game read additional tutorial lines from a map's `[Tutorial]` section: https://github.com/CnCNet/ts-patches/blob/master/src/text_triggers.c

However, the hack is partially bugged: it doesn't seem to work 100% of the time, and it also doesn't support saved games. If you play a map that has its own custom tutorial lines, then save the match and load it, the custom tutorial lines are gone.

**Comment by CCHyper** [comment]
Can someone link to where the ts-patches code referenced is hooked?

**Comment by CCHyper** [comment]
Information from @Rampastring;

> it's called here https://github.com/CnCNet/ts-patches/blob/master/src/spawner/spawner.asm#L335
> which is in _Read_Scenario_INI_Dont_Create_Units_Earlier
> 
> and...
> 
> @LJMP 0x005DDAF1, _Read_Scenario_INI_Dont_Create_Units_Earlier
> so it could be said that it's practically hooked in as a call from 0x005DDAF1
