### ISSUE TITLE
[New Feature] RA2-style destructible projectiles

### ISSUE THREAD

**Issue by CCTiberius** [Vinifera-Developers/Vinifera#147]
### Description:
Stuff like the V3 rockets which can be shot down mid-flight by anti-air weaponry could add some interesting nuances to a mod's balance.

### Possible Implementation:
Same as RA2. If you can't define how much it takes to destroy a projectile in RA2, it would be nice if it was added here.

**Comment by ZivDero** [comment]
Resolved in 744a245163e5e622a92621ca64ad3f929b637398
