### ISSUE TITLE
[New Feature] Auto-save on single-player mission start.

### ISSUE THREAD

**Issue by CCHyper** [Vinifera-Developers/Vinifera#148]
### Description:
In Red Alert 2, the game auto-saves at the start of every single-player mission. These save files use a different filename format than user saves. They use the name of the scenario file rather than randomly generating a filename. For example, playing the first GDI mission, GDI01, would produce a save file called `GDI01.SAV` when you start the mission. 

It would be ideal to use the same implementation that Red Alert 2 uses for the sake of simplicity. The only addition to the Red Alert 2 implementation would be to add an identifier "(Auto-save)" to the save file description.

**Comment by CCHyper** [comment]
It would be very easy to add a radio button to the dialog to show/hide these, and we could have them hidden by default.

**Comment by ZivDero** [comment]
Redundant with the CnCNet client.
