### ISSUE TITLE
[Vanilla Bug] Vinifera tiberium type has hardcoded Power=17

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#156]
### Description:
0x00644DCA hardcodes Vinifera to have Power=17 regardless of its actual specified power value in Rules.ini.

**Comment by CCHyper** [comment]
This would have been done by a programmer for one of the Tiberian Sun patches, most likely due to timing.

We would want to retain this of course, so perhaps a new INI section in `RULES.INI` where we can define keys to unhardcode similar cases would be the best solution.

**Comment by Rampastring** [comment]
I'd rather do it the other way around, ship Vinifera with a new INI file that contains the hardcoded patch changes and make the game load it in addition to Rules.ini / Firestrm.ini.

**Comment by CCHyper** [comment]
Good point, some of these limitations are outside of `RULES.INI` and new INI might be better here, but we do not want to ship an INI with our releases, it would be optional for the end-user/mod developer to create and define this file, and of course, we can document it in the Vinifera documentation.

**Comment by ZivDero** [comment]
Resolved in 53c013783aadfdaecc0edd7c678f7c96897a8127
