### ISSUE TITLE
[Vanilla Bug] Veterancy crates give veterancy to units with Trainable=no

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#161]
### Description:
Objects with `Trainable=no` shouldn't be able to gain veterancy. However, veterancy crates can still turn them veteran or elite.

### Additional Files:
Fixed in CnCNet ts-patches: https://github.com/CnCNet/ts-patches/blob/master/src/veterancy_crate_check_trainable.asm

**Comment by CCHyper** [comment]
After some research, I'm happy that this is in fact a bug.
