### ISSUE TITLE
[Vanilla Bug] Your objects gain XP / veterancy from destroying allied objects

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#162]
### Description:
You can turn your trainable units veteran and elite by destroying objects of your own or objects of your allies. This seems to go against the original veterancy feature design and is generally considered a bug.

### Additional Files:
Fixed in CnCNet ts-patches: https://github.com/CnCNet/ts-patches/blob/master/src/veterancy_from_allies.asm

**Comment by ZivDero** [comment]
Resolved in 0ebb25ff84b32a8b1f81950dfdecb81031ada4c8
