### ISSUE TITLE
[New Feature] Save screenshots as PNG files instead of PCX files

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#167]
### Description:
PCX is an unusual image format that is unsupported by many common image viewers. It would be more user-friendly if the game wrote PNGs instead.

### Additional Files:
CnCNet ts-patches has code for writing screenshots as PNGs instead of PCXs: https://github.com/CnCNet/ts-patches/blob/master/src/write_jpg_png.c

The LodePNG 3rd-party library is used for this purpose: https://github.com/CnCNet/ts-patches/tree/master/3rdparty

However, the ts-patches hack has a critical bug: while it correctly saves screenshots as PNGs instead of PCXs, it also causes the game to crash after the screenshot has been written.

**Comment by CCHyper** [comment]
Would everyone be happy if we replaced PCX with PNG completely? I think this is a QoL improvement that should be a replacement.
