### ISSUE TITLE
[New Feature] Hotkey for repeating the last building you built

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#168]
### Description:
CnCNet ts-patches implements a keyboard command that can be used for initiating production of the last building type that you placed. It is very useful and saves a lot of mouse clicks (especially together with #112 ) when you for example want to expand by building 5 power plants or quickly spam a bunch of defenses.

### Additional Files:
CnCNet ts-patches code: https://github.com/CnCNet/ts-patches/blob/master/src/repeat_last_building_hotkey.c

**Comment by CCHyper** [comment]
Maybe we could go further with this and have hotkeys for repeating the last Building, Unit, Infantry and Aircraft. I think these would be nice QoL additions for the online players.

**Comment by Rampastring** [comment]
I wouldn't be opposed to that, although it is most important for buildings because while you can queue infantry, vehicles and aircraft, you can't queue buildings.
