### ISSUE TITLE
[Vanilla Bug] AI players allied to you still send teams to 'attack' you

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#170]
### Description:
Quoting Iran from the C&C Mod Haven Discord:

> theres a bug in ts where ai players allied to you will still send attack teams to 'attack' you, i fixed it in ts-patches but i'm not sure what I modified. Didnt have the code documented so i cross referenced some ra1 houseclass attack wave stuff

### Additional Files:
Fix in CnCNet ts-patches, spawner.asm line 400 (at the time of writing this): https://github.com/CnCNet/ts-patches/blob/master/src/spawner/spawner.asm#L400
`@LJMP 0x004C06EF, _HouseClass__AI_Attack_Stuff_Alliance_Check`

**Comment by CCHyper** [comment]
When playing vanilla Tiberian Sun, what are the steps to reproduce this? As you can not ally with the AI in Skirmish for example...

**Comment by Rampastring** [comment]
I guess it might be impossible to reproduce this in pure vanilla TS without hacking in some kind of an AI alliance system. Maybe you can try some trigger magic to make a single AI allied to you in multiplayer, but that's an unreliable approach because you can't reliably refer to multiplayer houses using triggers in vanilla.

**Comment by CCHyper** [comment]
> I guess it might be impossible to reproduce this in pure vanilla TS without hacking in some kind of an AI alliance system. Maybe you can try some trigger magic to make a single AI allied to you in multiplayer, but that's an unreliable approach because you can't reliably refer to multiplayer houses using triggers in vanilla.

Although I can see this actually being a bug in the code and agree with the bug fix, we need to make sure we are fixing bugs from the approach of unmodded/vanilla Tiberian Sun where possible, this reduces the chances of edge case bugs appearing as a result.

Let's see if there is a way to reproduce this for sure first and then we can revisit it once again if there is no possible chance without modding the game/engine.

**Comment by ZivDero** [comment]
As far as I can see, this manifests the following way:
If an allied house is the closest to the AI, it will repeatedly set the allied house as the enemy, then instantly unset it as the enemy, and thus not attack anyone.

**Comment by ZivDero** [comment]
Fixed in f3f7e1fb7a7fcaf0f813c0efc9dfbed4d50283ab
