### ISSUE TITLE
[New Feature] Allow the game to run without MULTI.MIX or MAPS##.MIX

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#182]
### Description:
The game gives a "Failed to initialize, please reinstall" error message if MULTI.MIX or MAPS01/02.MIX is not found. Mods typically have both MP and SP maps stored in sub-directories and map selection is handled by the client, so they don't have any of these MIX files.

### Additional Files:
Fixed in CnCNet ts-patches: https://github.com/CnCNet/ts-patches/blob/master/src/mods/disable_file_checks.asm

**Comment by CCHyper** [comment]
Closing this issue in favour of merging with #110.
