### ISSUE TITLE
[New Feature] Display more pips

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#189]
### Description:
The game is limited to only displaying a specific amount of pips of a each type. For example, if you create an APC that can carry a much higher number of passengers than the usual of `5`, the game doesn't display pips for all of the passengers.

### Additional Files:
CnCNet ts-patches extends the pip count limitations: https://github.com/CnCNet/ts-patches/blob/master/src/mods/max_pip_counts.asm

**Comment by CCHyper** [comment]
Changed to feature request as this is modding related.
