### ISSUE TITLE
[New Feature] Write saved games to a sub-directory

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#194]
### Description:
To keep the main directory clear, most mods prefer it when the game writes its saved games to a sub-directory. The CnCNet client is also coded to read saved games from the `Saved Games` sub-directory.

### Additional Files:
CnCNet ts-patches implementation: https://github.com/CnCNet/ts-patches/blob/master/src/mods/saved_games_in_subdir.asm

**Comment by ZivDero** [comment]
Resolved in 53fb2f98d6dd5f0870b16dce381ed79f2adeb44b
