### ISSUE TITLE
[Vanilla Bug] Fix script action #4 to use TS logic for calculating coordinates

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#196]
### Description:
From E1 Elite:

> Script action 4 : Move to Cell.. (4,cell#) uses leftover logic from RA1 to compute coordinates.

### Additional Files:
Fixed in CnCNet ts-patches: https://github.com/CnCNet/ts-patches/blob/master/src/mods/scriptaction4.asm

With the fix, the script action uses the TS logic for calculating coordinates instead, which makes the script action support larger map sizes.

**Comment by CCHyper** [comment]
Does this have any impact on vanilla Tiberian Sun single-player missions?

**Comment by E1Elite** [comment]
None of vanilla SP maps use this script action.

**Comment by CCHyper** [comment]
Test map courtesy of @E1Elite for assisting in testing a possible fix.

Attachment:
[movetocell_testmap.zip](https://github.com/Vinifera-Developers/Vinifera/files/6630957/movetocell_testmap.zip)
