### ISSUE TITLE
[New Feature] Unhardcode Tiberium damage divisor

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#200]
### Description:
Tiberium damage has some hardcoded properties that are undesirable for DTA (and probably for other mods as well).

1) 0x000D3F75 contains a hardcoded divisor for tiberium damage
2) Tiberium with Power=0 causes a crash (IIRC), while it should just do 0 damage

CnCNet ts-patches adjusts / fixes these:
https://github.com/CnCNet/ts-patches/blob/master/src/mods/tiberium_damage.asm

**Comment by CCHyper** [comment]
A new key for TiberiumClass would be able to provide a custom damage divisor. But I would suggest splitting out the `Power=0` crash so this can easily be tracked and tested.

**Comment by Rampastring** [comment]
DTA actually has a custom version of this hack that changes the damage divisor into a damage multiplier instead: https://github.com/CnCNet/ts-patches/blob/master/src/mods/dta/tiberium_damage.asm

**Comment by ZivDero** [comment]
Resolved by 53c013783aadfdaecc0edd7c678f7c96897a8127
