### ISSUE TITLE
[New Feature] Individual Reload Times

### ISSUE THREAD

**Issue by CCTiberius** [Vinifera-Developers/Vinifera#204]
### Description:
Make it possible to set how long a unit takes to reload its ammo, instead of it being a global.

### Possible Implementation:
Same system as now just individual for each unit. You could have a global that sets the baseline, and then a key that speed up or slows down reload for that unit, so for example if a unit had `ReloadFactor=1.2` it would reload 20% faster than normal.

**Comment by Crimsonum** [comment]
There's already the key `Reload` for TechnoTypes, could use that and fix whatever problems it had.
