### ISSUE TITLE
[New Feature] Automatic deploying of starting MCV

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#206]
### Description:
In some special multiplayer scenarios (like certain co-op missions) it's desirable for the starting MCV to get automatically deployed at game start.

### Additional Files:
CnCNet ts-patches implentation: https://github.com/CnCNet/ts-patches/blob/master/src/mods/dta/auto_deploy_mcv.asm

There is a new session variable (for us it could be in the SessionClass extension), `AutoDeployMCV` that is read from `spawn.ini`.

**Comment by CCHyper** [comment]
In addition to this, I have unreleased HyperPatch code that contains a patch for re-placing the Construction Yard. IT would save a couple of seconds on game start by having them replaced.

Alternatively, we could implement both `AutoDeployMCV` and `PreplacedConYards` to give more options to the mod developer.

**Comment by Rampastring** [comment]
I think the keys would practically achieve the same effect, aside from special scenarios where there's something preplaced next to a MCV and it can't be deployed with `AutoDeployMCV`. I can't currently think of a case where doing that would be very beneficial for a mission designer though, so I think `PreplacedConYards` is more important.
