### ISSUE TITLE
[New Feature] Customizable score screen music

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#207]
### Description:
Dawn of the Tiberium Age requires the score screen music to be customizable per-faction. GDI and Nod use the Tiberian Dawn score screen music, while the Allies and Soviets use the Red Alert score screen music.

### Additional Files:
CnCNet ts-patches implementation using hard-coded music track ID strings and side indexes: https://github.com/CnCNet/ts-patches/blob/master/src/mods/dta/change_score_screen_music.asm

**Comment by CCHyper** [comment]
Perhaps a new HouseType INI key, `ScoreTheme=<ThemeType>` on HouseType entries in RULES.INI is the best solution here.

**Comment by CCHyper** [comment]
After checking the loading process again, it has been confirmed that `SIDEC##.MIX` can be used to override the Score theme for side-specific purposes _(providing the file is not found elsewhere in the game mix files)_. Thanks to @Bittah testing. 

Closing this issue.
