### ISSUE TITLE
[New Feature] Make it possible to prevent a vehicle from being picked up by Carryalls

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#208]
### Description:
CnCNet ts-patches has a hack that replaces `CloakStop` with `TooBigForCarryalls`. If set for a `UnitTypeClass`, units of the type cannot be picked up by carryalls.

### Additional Files:
CnCNet ts-patches implementation: https://github.com/CnCNet/ts-patches/blob/master/src/mods/dta/cloakstop_to_toobigforcarryalls.asm

**Comment by CCHyper** [comment]
Thankfully, we can add new TypeClass INI keys, so a new INI key with associated logic would be ideal here.
