### ISSUE TITLE
[New Feature] Allow changing the default value of IsScoreShuffle to true

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#212]
### Description:
From CnCNet ts-patches / DTA:

```
;; IsScoreShuffle on by default
@SET 0x005899F1, {mov byte [eax+35h], 1} ;byte ptr
@SET 0x005899F5, nop
@SET 0x005899F6, nop
@SET 0x005899F7, nop
```

**Comment by CCHyper** [comment]
I would actually vote to change this to a bug fix and make this the new default setting.

**Comment by CCHyper** [comment]
Are we happy for this to become a QoL change and be the new default setting?

**Comment by Rampastring** [comment]
I don't have a strong opinion on this. Some players might enjoy hearing specific tracks at specific phases of the game (like starting the match with Valves). But the average player probably wouldn't mind `IsScoreShuffle` being on by default as they could still change it themselves if they preferred hearing the tracks in order.
