### ISSUE TITLE
[New Feature] Support for more than 8 facings

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#214]
### Description:
Units in DTA have 32 facings. DTA / CnCNet ts-patches implementation:

```
@SET 0x006530EB, {cmp dword [eax+4CCh], 20h} ;dword ptr
@SET 0x00653106, {shr ebx, 0Ah}
@SET 0x0065310D, {and ebx, 1Fh}
```

**Comment by CCHyper** [comment]
This is a tricky item, as the hack I wrote here for DTA actually requires editing of the units shape graphic and offsetting it by a couple of frames.

Approaching this feature from a new angle and writing it correctly would be the correct way to implement support for more than 8 facings.

**Comment by Bittah** [comment]
@CCHyper You once mentioned that a future 32-facing patch could could use something like Facings=0 to revert to the old method with the facings offset by 3 frames. Is that still an option?

**Comment by CCHyper** [comment]
> @CCHyper You once mentioned that a future 32-facing patch could use something like Facings=0 to revert to the old method with the facings offset by 3 frames. Is that still an option?

While this is indeed possible, introducing and supporting undefined behaviour opens the project up to allowing new bugs/edge cases to creep in.

**Comment by Rampastring** [comment]
The problem with that is that DTA has a ton of unit graphics that will need to be modified to account for the change in logic. @Bittah will have to figure out whether it's something that can be realistically done.

(Maybe it could be done algorithmically, iow. a program could be written for that?)

**Comment by Bittah** [comment]
I actually assumed that it should be doable if I'd just plow through it for a couple days, but it looks like I actually underestimated how many SHPs I'd have to edit; being 220 in total.

> While this is indeed possible, introducing and supporting undefined behaviour opens the project up to allowing new bugs/edge cases to creep in.

How about adding a key like North=29 (and defaults to North=0) that specifies which facing represents North?

**Comment by CCHyper** [comment]
> How about adding a key like North=29 (defaults to North=0) that specifies which facing represents North?

This would be adding unnecessary features, and will most likely require a lot more code to handle.

It would be best to look into automating the process as @Rampastring mentioned or correcting the shape files  manually while Vinifera is still in its early stages of development.

**Comment by Bittah** [comment]
Another related issue that I should mention is that the frames on which the turret appears are hardcoded and it'd be helpful if there was a StartTurretFrame= key to make it possible to specify a different starting frame for them (currently you need to multiply WalkFrames by 8 to know on which frame the turret starts), so with WalkFrames=1 the turret starts from the 9th frame).

**Comment by CCHyper** [comment]
> Another related issue that I should mention is that the frames on which the turret appears are hardcoded and it'd be helpful if there was a StartTurretFrame= key to make it possible to specify a different starting frame for them (currently you need to multiply WalkFrames by 8 to know on which frame the turret starts, so with WalkFrames=1 the turret starts from the 9th frame).

@Bittah, could you create a new bug-fix/feature request for this, please? Just so we can track it individually.

**Comment by CCHyper** [comment]
Attached are two SHP files converted from RA1, both units without turret frames. Prepared by @Bittah;

16 Facings;
[harv.zip](https://github.com/Vinifera-Developers/Vinifera/files/6694700/harv.zip)

32 Facings;
[mcv.zip](https://github.com/Vinifera-Developers/Vinifera/files/6694704/mcv.zip)

**Comment by CCHyper** [comment]
Courtesy of 4SG;

32 facings _(3 walk frames)_ and 64 _(1 walk frame)_ facings unit with a turret.
[apocshps.zip](https://github.com/Vinifera-Developers/Vinifera/files/6704702/apocshps.zip)
