### ISSUE TITLE
[New Feature] Unhardcode Tiberiums with Image=2 using 1 frame per overlay

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#217]
### Description:
I have no idea what this actually does, but it's on CnCNet ts-patches and enabled in DTA:

```
@SET 0x00644DF9, {mov dword [esi+0ACh], 0Ch}
```

**Comment by tomsons26** [comment]
Number of frames for  Image=2 Tiberium, original is 1, all other Tiberiums have 12

**Comment by ZivDero** [comment]
Done in 53c013783aadfdaecc0edd7c678f7c96897a8127
