### ISSUE TITLE
[New Feature] Enable the game to write a debug log to the game directory

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#225]
### Description:
Vanilla TS has debug logging disabled by making the debug print function just return instantly. CnCNet ts-patches has a hack that makes the game write debug lines to a log file instead. The debug log put out by the game is parsed by the client after a match to figure out the stats of all players (if the game was completed). The name of this debug log varies between mods/games: for DTA it's `DTA.LOG`, for TI it's `TI.LOG` and for the TS client it's `TS.LOG`.

### Additional Files:
CnCNet ts-patches implementation: https://github.com/CnCNet/ts-patches/blob/master/src/mods/dta/logger.asm
(don't look too seriously at it, it's almost the first ASM I ever wrote and copied from a previous community patch that I had no source code access to :V )

**Comment by CCHyper** [comment]
Vinifera implements a debug logging system already, it has both file output and console output (developer mode).

As for a custom filename, I feel this is a vanity change. We should not be catering to specific projects for such a debugging system that needs to be universal and easily interpreted by developers and contributors.

The output of the states information would need to be its own new feature request as that would ideally be written to its own file.
