### ISSUE TITLE
[Vanilla Bug] Various issues in Get_RDTSC_CPU_Speed

### ISSUE THREAD

**Issue by tomsons26** [Vinifera-Developers/Vinifera#233]
### Description:

This function tends to have quite a number of issues, most common is a division by 0.
Further investigation and checks if Intel ever updated this function to fix issues are needed.
### Conditions:

Currently unknown.

### Steps To Reproduce:

Just starting the game and being unlucky.

Pentium Dual Core e2200 seems to be one known CPU this happens on.

**Comment by CCHyper** [comment]
`Get_RDTSC_CPU_Speed` is not used in Tiberian Sun, this looks to be a Red Alert 2 issue only.
