### ISSUE TITLE
[Vanilla Bug] Keyboard does not check if input is locked when processing hotkey commands.

### ISSUE THREAD

**Issue by CCHyper** [Vinifera-Developers/Vinifera#255]
### Description:
The keyboard process loop does not check if the input is locked when processing hotkey commands, as a result, the player can affect the game in certain situations when the lock input trigger has been executed.

### Ideal Behaviour:
All hotkeys other than "Options" should be disabled.

### Possible Fix:
This can be implemented by checking if the input locked flag is set, and only allowing a hotkey command that matches the "Options" to be executed. `Keyboard_Process()` is inlined in `Main_Loop()`, this check should be done just after the call to `GScreenClass::Input()`.

**Comment by Rampastring** [comment]
`Main_Loop` is not the only place where `Keyboard_Process` is inlined. It is also inlined in two different locations of `Sync_Delay`, those need to be patched as well.

Furthermore, `Keyboard_Process` itself is called in `Wait_For_Players`, which means that `Keyboard_Process` itself needs to be patched too.
