### ISSUE TITLE
[New Feature] Produce Cash logic

### ISSUE THREAD

**Issue by CCHyper** [Vinifera-Developers/Vinifera#26]
### Description:
The produce cash logic drives the Oil Derricks in Red Alert 2. Port this system over to Tiberian Sun with some additional options described below.

### Possible Implementation:
``ProduceCashStartup=<integer>`` Amount of credits given to the capturing house when this building is captured.
``ProduceCashAmount=<integer>`` The number of credits to grant every delay cycle.
``ProduceCashDelay=<integer>`` The frame delay between each credits bonus.
``ProduceCashBudget=<integer>`` The total available budget for this building.
``ProduceCashRequiresPower=<boolean>`` Does this building require power to produce credits?
``ProduceCashIsNegative=<boolean>`` Does it drain credits from the house instead of giving granting them?

Open to discussion.

**Comment by Rampastring** [comment]
Might it be fitting to just use `Powered` instead of having a separate `ProduceCashRequiresPower` key?

**Comment by CCHyper** [comment]
> Might it be fitting to just use `Powered` instead of having a separate `ProduceCashRequiresPower` key?

My thinking was that if `Powered` was true, then `ProduceCashRequiresPower` could be false to the produce cash system to still operate if the building is offline or in the lower power state. Or would this be redundant?

**Comment by Rampastring** [comment]
I personally think it'd be redundant.

Also regarding `ProduceCashIsNegative`, wouldn't it work to just input negative values for the various cash keys instead?

**Comment by CCHyper** [comment]
> I personally think it'd be redundant.
> 
> Also regarding `ProduceCashIsNegative`, wouldn't it work to just input negative values for the various cash keys instead? For example `ProductCashAmount=-20`

I would be happy to implement the system to support a negative `ProductCashAmount=`, which makes more sense.

**Comment by CCHyper** [comment]
Would modders like the option to show cloud tooltips above the build each time a cash bonus is granted?

**Comment by Crimsonum** [comment]
> Would modders like the option to show cloud tooltips above the building each time a cash bonus is granted?

You mean like in for example Generals?
https://youtu.be/hXxcGkq5eYs?t=113

I think it would be a great addition to the logic.

**Comment by CCHyper** [comment]
This is exactly what I had in mind, the only technical limitation might be the "fade out" effect you see in that video, we are not sure if the game supports rendering text with transparency.
