### ISSUE TITLE
[New Feature] Add a "Load Game" button into the "Would you like to replay the mission?" dialog

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#269]
### Description:
When you fail a mission, the game asks you "Would you like to replay the mission?" offering options to restart or quit to the main menu. In longer missions, however, you tend to create saves as you progress, and when you fail, you usually want to continue the mission from one of those saves instead of starting over each time. This "Would you like to replay the mission?" dialog currently offers no option to load the game, which makes it largely a waste of time and annoyance for longer missions.

To fix it, the dialog should get a "Load Game" button added into it. The official C&C Remasters also make this QoL improvement.

### Possible Implementation:
I'm not certain on whether the dialog is stored in Language.dll. Regardless of whether it is, or not, the game needs logic for handling clicks on a "Load Game" button in the dialog. If the dialog is stored in Language.dll, then the DLL also needs to be edited for the button to be added there.

Thinking about it, such a dialog could be easily created like the standard Windows Forms MessageBox assuming the game's GDI (graphics device interface) UI can display those, so it's also possible that the dialog is created dynamically.

**Comment by CCHyper** [comment]
Screenshot for reference:
![image](https://user-images.githubusercontent.com/73803386/120714225-d74c6000-c4ba-11eb-9c4b-836a5850a57b.png)

 I guess the "Load Game" button can be added to the enter space?

**Comment by Rampastring** [comment]
You mean in between the buttons? Yeah, I think there's a fitting space.
