### ISSUE TITLE
[Vanilla Bug] C4 can destroy almost anything via force-firing

### ISSUE THREAD

**Issue by Crimsonum** [Vinifera-Developers/Vinifera#274]
### Description:
Infantry units with `C4=` set can target & destroy _any_ building through force-firing, except bridge repair huts. This includes special buildings like the laser fence's lasers, producing a gap in the fence and allowing players to cheese through certain missions, for example GDI's Power Grid mission, where the laser fences are intended to trap the Ghost Stalker.

TS-patches works around this by preventing units from targeting buildings with `Repairable=no`:
https://github.com/CnCNet/ts-patches/blob/d955694df6c9ca53cc2d1903825c2e1c120bb75c/src/c4_repairable_fix.asm

It might be preferable to combine this with `LegalTarget=no` and/or have a unique key for this, like `ImmuneToC4=`.

**Comment by Bittah** [comment]
Closed in favor of #614.
