### ISSUE TITLE
[New Feature] Allow customising TechnoType build speed

### ISSUE THREAD

**Issue by Crimsonum** [Vinifera-Developers/Vinifera#276]
### Description:
The rate at which buildings and units are constructed depends on the general setting `BuildSpeed` and is proportional to the object's cost. Walls have an additional modifier, `WallBuildSpeedCoefficient`. It would be beneficial to let modders customize build speed for each object separately. For example, in TD, different buildings have different build speeds, regardless of their cost.

### Possible Implementation:
Allow `BuildSpeed=` to be defined for any TechnoType. If no value is found, use the default value found in `[General]->BuildSpeed=`.

**Comment by CCHyper** [comment]
Closes this issue in favour of #433.
