### ISSUE TITLE
[Vanilla Bug] Bugs with Battle(FS).ini

### ISSUE THREAD

**Issue by MikillRosen** [Vinifera-Developers/Vinifera#300]
### Description:
Note: I'm using the freeware release of TS.
Things get buggy when you add a third campaign or more to Battle(FS).ini. There are also bugs and unwanted features about the `CD` INI flag.
It seems that the game ignores an INI flag if they are placed at the last line in Battle(FS).ini. But if you add an empty line as the last line, the issue gets fixed.
In a new campaign, a mission can't progress to the next one ("Unable to Initiate Map Selection" error). Putting the missions in Mission(1).ini and MapSel(01).ini doesn't fix this.
The `CD` INI flag determines which House's loading screen is used and (depending on the value) which intro movie should be played at the start of a campaign. These features are unwanted and `CD` should only determine which disk is required. (0 for GDI disk, 1 for Nod disk, 2 for Firestorm disk, and -1 for no disk required.)

### Expected Behaviour:
Missions from new campaigns should be able to progress to the next mission without problems.
`CD` should only determine which disk is required.

### Actual Behaviour:
Missions from new campaigns can't progress to the next mission
`CD` determines which disk is required, but it also determines which faction's loading screen is used and which faction's intro movie is played.

### Additional Files:
[battle.ini bugs.zip](https://github.com/Vinifera-Developers/Vinifera/files/6620171/battle.ini.bugs.zip)
TS tutorial missions are from the TS demo.
Operation: Exodus by Zero18 (https://ppmforums.com/topic-34609/fs-gdi-campaign-operation-exodus/)
Ghosts of the Past by EliteCadre (https://ppmforums.com/topic-47215/fs-ghosts-of-the-past/)

**Comment by CCHyper** [comment]
_In regards to the issue of the new campaign entry not appearing in the in-game listing._

After further testing, the INI files were missing an empty line/blank line at the end. This is a limitation with the games INI engine and causes the last line not to be read from the file.

Closing issue.
