### ISSUE TITLE
[Vanilla Bug] Custom campaign mission progression doesn't work.

### ISSUE THREAD

**Issue by MikillRosen** [Vinifera-Developers/Vinifera#302]
### Description:
In a custom campaign, a mission can't progress to the next one ("Unable to Initiate Map Selection" error). Putting the missions in Mission(1).ini and MapSel(01).ini doesn't fix this.

### Expected Behaviour:
Missions from custom campaigns should be able to progress to the next mission without problems.

### Actual Behaviour:
Missions from custom campaigns can't progress to the next mission

### Additional Files:
[Demo campaign.zip](https://github.com/Vinifera-Developers/Vinifera/files/6626770/Demo.campaign.zip)

**Comment by Rampastring** [comment]
Dawn of the Tiberium Age has 4 custom campaigns (including branching missions) and mission progression works fine there. I'd assume this to be a case of miconfiguration unless proven otherwise.

**Comment by MikillRosen** [comment]
I'm sure I configured the missions correctly, it's just the game refuses to progress to the next mission because it doesn't support campaigns outside the official campaigns. You probably used patches to fix this in DTA. If you still think I did something wrong, how about you do it yourself and if you succeed, tell me how you did it.
