### ISSUE TITLE
[New Feature] Seeing your own chat messages

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#37]
### Description:
Original Tiberian Sun does not display chat messages that you have sent, which is confusing to new players and leads them wondering whether their message was actually sent. All more modern games with chat display your own messages as well.

### Additional Files:
Implemented in CnCNet ts-patches: https://github.com/CnCNet/ts-patches/blob/master/src/display_messages_typed_by_yourself.asm

**Comment by CCHyper** [comment]
I think this would be a great QoL change that should be the new default behaviour. It seems to be the standard in most games now.

Any objections?

**Comment by Rampastring** [comment]
This has been in ts-patches for 5 years and I haven't seen a single objection regarding it.

**Comment by CCHyper** [comment]
Do we have information as to who the original author of this patch was?
