### ISSUE TITLE
[New Feature] Queue 5 units at once.

### ISSUE THREAD

**Issue by Lylaktech** [Vinifera-Developers/Vinifera#376]
### Description:
When Pressing a Hotkey and left clicking a unit, it will queue 5 instances of that unit instead of 1, speeds up the process, saves your finger the cramps and especially helps when online lag is involved.

**Comment by Metadorius** [comment]
The code should be in Ares. Basically what it does is when shift is pressed and the gadget is clicked it sends 5 events instead of one. That's how we described the idea for Alex to implement back then and he agreed it made sense, shortly after it appeared in one of devbuilds.

**Comment by ZivDero** [comment]
Resolved in b6f7e2d8e6c453bca1ad3cb5943eb322d3792872
