### ISSUE TITLE
[New Feature] StartTurretFrame=

### ISSUE THREAD

**Issue by Bittah** [Vinifera-Developers/Vinifera#389]
### Description:
In TS the frame number where the turret frames start is hardcoded (to 8 * WalkFrames +1). It would be useful to be able to specify from which frame number the turret frames start like you can already do with WalkFrames, FiringFrames, StandingFrames, etc.

### Possible Implementation:
Allow `StartTurretFrame=` to be used in art.ini.

**Comment by CCHyper** [comment]
If Tiberian Sun currently expects all units to have 32 facings for their turrets, then it would be best to default this new value to 32.
