### ISSUE TITLE
[New Feature] Ability to rebind Q-move hotkey.

### ISSUE THREAD

**Issue by Lylaktech** [Vinifera-Developers/Vinifera#40]
### Description:
Q-move is currently the only hotkey in TS (as far as I can see anyway) that you can't re-bind to another hotkey, would be great if one was able to set it to whatever they want.

**Comment by Metadorius** [comment]
I second this because it's a pain to switch between TS and YR mods and having to readjust to Z key being a hotkey for placing building and Q for q-move, while in YR it's Q for buildings tab switch / placement and Z for waypoint mode.

**Comment by Rampastring** [comment]
This has been made possible with the new sidebar implementation, with a changed default hotkey for q-move to `Z`.
