### ISSUE TITLE
[New Feature] Adjustable buildspeeds for objects, independent of their cost

### ISSUE THREAD

**Issue by Bittah** [Vinifera-Developers/Vinifera#433]
### Description:
A key that controls the buildspeed of a unit or structure so that it can be produced faster or slower than similar units or structures with the same price (similar to how Refineries in TD are produced much faster than War Factories, even though they both cost 2000 credits).

### Possible Implementation:
A `BuiltTime` key for which works the same as Cost for the object's build time. So a War Factory with `Cost=2000` and `BuildTime=600` will take the same amount of time to produce as a structure with `Cost=600`.

**Comment by E1Elite** [comment]
Title could say buildspeed instead of just speed.

**Comment by nucspl** [comment]
I was about to make a new issue for YR `BuildTimeMultiplier`, but this appears to be better.

**Comment by CCHyper** [comment]
Merging issue #276 into this issue;

From @Crimsonum

> ### Description:
> The rate at which buildings and units are constructed depends on the general setting `BuildSpeed` and is proportional to the object's cost. Walls have an additional modifier, `WallBuildSpeedCoefficient`. It would be beneficial to let modders customize build speed for each object separately. For example, in TD, different buildings have different build speeds, regardless of their cost.
> ### Possible Implementation:
> Allow `BuildSpeed=` to be defined for any TechnoType. If no value is found, use the default value found in `[General]->BuildSpeed=`.
