### ISSUE TITLE
[New Feature] Mechanics

### ISSUE THREAD

**Issue by Bittah** [Vinifera-Developers/Vinifera#440]
### Description:
Infantry that can repair vehicles, as well as displaying the red cross pip like the medic. Rampastring already implemented this into ts-patches.

### Possible Implementation:
Same as in RA1

### Additional Files:
https://github.com/CnCNet/ts-patches/blob/master/src/mods/dta/mechanics.asm

**Comment by Rampastring** [comment]
Duplicate of #226
