### ISSUE TITLE
[New Feature] TerrainType objects that can produce light.

### ISSUE THREAD

**Issue by CCHyper** [Vinifera-Developers/Vinifera#452]
### Description:
Only BuildingType objects can currently produce lighting. Allowing TerrainType objects to produce light would remove the requirement for invisible light posts in Tiberium fields.

### Possible Implementation:
Exactly how it works currently for BuildingTypes;
`LightIntensity=` - This building radiates this amount of light (def = 0).
`LightVisibility=` - The distance (in leptons) that this light is visible from (def = 5000).
`LightRedTint=` - The red tint of this buildings light (def = 1.0).
`LightGreenTint=` - The green tint of this buildings light (def = 1.0).
`LightBlueTint=` - The blue tint of this buildings light (def = 1.0).

**Comment by MikillRosen** [comment]
They should also be able to use alpha lights

**Comment by Crimsonum** [comment]
> They should also be able to use alpha lights

You can already attach alpha lights to terrain types the same way you attach them to buildings. See for example TI's light posts (streetlights).

**Comment by MikillRosen** [comment]
Oh I forgot.
