### ISSUE TITLE
[Vanilla Bug] Sticky Tech bug

### ISSUE THREAD

**Issue by MikillRosen** [Vinifera-Developers/Vinifera#454]
### Description:
The infamous Sticky Tech bug allows you to sell your tech center without losing the new tech you just got. For some reason, some people believe this is a feature. If it is, I'll launch a nuclear strike on the former Westwood employees for making such a retarded feature.

### Steps To Reproduce:
1. Build a tech center
2. Sell your tech center

### Expected Behaviour:
You'll lose the new tech you just got

### Actual Behaviour:
You keep your new tech.

**Comment by Metadorius** [comment]
Duplicate of #85.
