### ISSUE TITLE
[Vanilla Bug] Fix mission restart difficulty reset bug

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#46]
### Description:
When the user restarts the first mission of a campaign (or a single non-campaign mission) through Options -> Abort Mission -> Restart, the player house's difficulty level gets reseted to Normal from whatever they had selected in the mission selector (or, nowadays, in the client).

### Steps To Reproduce:

1. Edit Rules.ini [Difficult], set the cost multiplier to be something higher than 1.0.
2. Start a campaign mission on Hard, notice objects costing more than usual for you.
3. Go to Options -> Abort Mission -> Restart (or lose the mission and restart it through the "Would you like to replay the mission" dialog)
4. Suddenly things cost normal for you again, like you had selected Normal as your difficulty level instead of Hard.

### Additional Files:
Fix in CnCNet ts-patches: https://github.com/CnCNet/ts-patches/blob/master/src/fix_mission_restart_difficulty_bug.asm

**Comment by CCHyper** [comment]
This is an interesting issue, and I believe the fix should be elsewhere, perhaps it is here 00493906 where it should save the correct difficulty, rather than removing the call to to HouseClass::Assign_Handicap() in Load (004939A5) which the patch does.

**Comment by Rampastring** [comment]
`EndGameClass::Save (004938A0)` is only called from `Do_Win`, while `EndGameClass::Load (00493920)` is also called from `Do_Lose` and `Do_Restart`. The save function saves the human player's difficulty at `00493909`, but if you restart the first mission of a campaign, (either directly through the menu or after losing the mission), the save function never gets called, while the load function is called.

The `EndGameClass` constructor initializes the human player's difficulty to `1` at `00493872`. Together with what I wrote above, this means that the human player's difficulty is always reset to normal when you restart the first mission of a campaign.

**Comment by CCHyper** [comment]
Upon further discussion, it seems the best solution where would be to fetch `Scen.Difficulty` in the `EndGameClass` constructor and use that to initialise the `EndGameClass` difficulty value.
