### ISSUE TITLE
[New Feature] Support old 32 facing SHPs

### ISSUE THREAD

**Issue by MikillRosen** [Vinifera-Developers/Vinifera#477]
### Description:
Since the `Facings=` INI flag is fixed, it unfortunately doesn't support the 32 facing SHPs that have the first frame face North-East of the screen.

### Possible Implementation:
Add `OldFacing=` in art.ini which makes the game handle an SHP differently by making the North-East facing the first facing. It accepts `yes` and `no`.

**Comment by CCHyper** [comment]
Unfortunately, we won't be supporting the old facings "hack", we discussed this topic in issue #214.

The best solution for this would be to fix up the old SHP files and produce a patch for any mods that use the old hack, but will be switching to Vinifera.

Closing issue.
