### ISSUE TITLE
[New Feature] Add support for PCX image files to be used as sidebar cameos.

### ISSUE THREAD

**Issue by CCHyper** [Vinifera-Developers/Vinifera#487]
### Description:
Add support for PCX image files to be used as sidebar cameos.

### Possible Implementation:
The system should not need any other user changes other than adding a PCX file with the same name to the games mix files.

**Comment by Metadorius** [comment]
In YR it's accessible dead easy, implemented in Phobos in one hook: https://github.com/Phobos-developers/Phobos/blob/develop/src/Misc/Hooks.PCX.cpp#L6
