### ISSUE TITLE
[New Feature] Allow the score screen to be skipped in multiplayer games.

### ISSUE THREAD

**Issue by CCHyper** [Vinifera-Developers/Vinifera#522]
### Description:
Allow the score screen to be skipped at the end of multiplayer games.

### Possible Implementation:
The cleanest solution would be to have the multiplayer score screen to honour the value of `ScoreSkip=` from the maps `[Basic]` section.

**Comment by Rampastring** [comment]
Following the single-player `ScoreSkip=` would make the feature map-dependant, which is not a great idea. You might want to skip the score screen on one occasion when playing a map, and see the score screen when you play the same map some other time.

One case where this can happen is the CnCNet clients. Currently FunkyFr3sh's client has a custom score screen, while my client doesn't. As a result Funky's client enables the CnCNet spawner flag for skipping the score screen, while my client doesn't.
