### ISSUE TITLE
[New Feature] Pressing G (Guard) on harvesters should make them harvest

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#53]
### Description:
Ordinary harvesters are unarmed and thus are not considered when executing the Guard Command. CnCNet ts-patches has a hack which adds exceptions for Harvester=yes and Weeder=yes.

### Possible Implementation:
CnCNet implementation: https://github.com/CnCNet/ts-patches/blob/master/src/harvesters_guardcommand.asm

**Comment by CCHyper** [comment]
Just so I understand, this is to make a Harvester that has been given a move order recently, begin the harvesting mission again without having to find a patch and order them manually?

**Comment by Rampastring** [comment]
When you've moved a Harvester recently and it is not harvesting, you can select it and press G (for the "Area Guard" command) to make it seek for tiberium to harvest again, without having to manually command it to a tiberium field.
