### ISSUE TITLE
[New Feature] Newly built start Harvesters should start harvesting automatically.

### ISSUE THREAD

**Issue by CCHyper** [Vinifera-Developers/Vinifera#6]
### Description:
Harvesters built from a war factory should start harvesting automatically. This was a QOL change in Red Alert 2.

### Possible Implementation:
This can be implemented in one of two ways;

- Changing the default behaviour of all Harvesters to act this way.
- Add a new INI key for the UnitTypes, for example; ``AutoHarvest=<boolean>``

Open to discussion.

**Comment by Rampastring** [comment]
This has been implemented in CnCNet ts-patches for a while. https://github.com/CnCNet/ts-patches/blob/master/src/harvesters_autoharvest.asm

**Comment by CCHyper** [comment]
Is everyone happy with this being a QoL improvement making all Harvesters act this way?

Or is a new UnitType INI key desired?

**Comment by Metadorius** [comment]
This is definitely a QoL improvement. Purists would argue but they are not gonna touch Vinifera so I don't think anyone would argue against this being a bugfix.

**Comment by tomsons26** [comment]
Yeah, its been like that since D2, but at some point was broken, in all games they should be harvesting.
https://github.com/electronicarts/CnC_Remastered_Collection/blob/master/REDALERT/UDATA.CPP#L338
