### ISSUE TITLE
[New Feature] Possibility to make names of AI players reflect their difficulty instead of being just "Computer"

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#617]
### Description:
Unlike the original game, the CnCNet Client allows you to define AI difficulty separately for each AI player. It'd be nice if these AI players could be named respective to their difficulty ("Easy AI", "Medium AI", "Hard AI") instead of them all having "Computer" as their name.

**Comment by ZivDero** [comment]
Resolved in 42a120fc27b25747a927d402939b402752b2f5a7
