### ISSUE TITLE
[New Feature] More waypoints.

### ISSUE THREAD

**Issue by E1Elite** [Vinifera-Developers/Vinifera#71]
### Description:
TS has 0-100 (101 total) waypoints available for use. Mappers specially single player mission creators feel that amount is small. It would be comfortable to have 702 waypoints as is available in YR.

### Possible Implementation:
Re-allocate larger array space for waypoints and alter its references.

**Comment by CCHyper** [comment]
Great feature request, should be very simple to do.

But just a curious question, has any ever reached the max size of 702 in Yuri's Revenge?
