### ISSUE TITLE
[Vanilla Bug] Factories infiltrated with a spy display their cameo using the wrong palette

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#72]
### Description:
When you infiltrate an enemy factory with a Spy and then select the factory, the unit that the factory is producing is displayed to you. However the game doesn't use the cameo palette for drawing the cameo.

### Additional Files:
Fixed in HyperPatch as part of CnCNet ts-patches: https://github.com/CnCNet/ts-patches/blob/master/src/hp03.asm

**Comment by CCHyper** [comment]
It's been quite some time since I wrote that fix...

What is the easiest and fastest way to reproduce this bug?

**Comment by Rampastring** [comment]
Add `Infiltrate=yes` (and `Agent=yes`?) to some infantry type and then infiltrate an enemy factory with it.

To further make it easier, just give the infantry type `Immune=yes` or `Disguised=yes` so the AI cannot kill it (AI doesn't target disguised infantry in vanilla TS, although it does with CnCNet ts-patches).

**Comment by CCHyper** [comment]
Screenshot for archiving purposes.
![image](https://user-images.githubusercontent.com/73803386/122216622-81a58980-cea4-11eb-8bf2-c0fceec3c4dd.png)

**Comment by MikillRosen** [comment]
Also, it uses palette.pal.
