### ISSUE TITLE
[New Feature] Background color for chat messages

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#74]
### Description:
Chat of other players is sometimes hard to read due to the transparent background of the message list. This can happen, for example, when a player uses a blue color and there happens to be water under the chat area on the top-left part of your screen. Having a background color for the chat messages significantly helps readability.

### Possible Implementation:
An option could be added for the user to choose from different message list background colors through SUN.ini.

### Additional Files:
Implemented in CnCNet ts-patches: https://github.com/CnCNet/ts-patches/blob/master/src/in-game_message_background.asm

**Comment by CCHyper** [comment]
Great QoL feature, and it might be possible to have the background transparent too.

My only concern would be if the background colour is set to black, and the player chooses a very dark shade, they are then stuck in the game with that setting unless everyone votes to restart the game.

Perhaps we add an in-game dropdown or toggle to the options dialog for this feature?

**Comment by Rampastring** [comment]
Very dark shades are bad even with a transparent background, as they are very hard to read against shroud. I'd say it's up to the mod author(s) to keep the colors bright enough, unless we made the game somehow brighten up dark colors for the chat.

**Comment by CCHyper** [comment]
The text print system in Tiberian Sun is still primitive like Red Alert, it's only Red Alert 2 that allows an RGB value to be passed in. So adjusting these would be locked to the `[Colors]` section in the RULES.INI.

Perhaps we can keep this one open to discussion and research before a decision is made.
