### ISSUE TITLE
[Vanilla Bug] Too large and detailed maps are not entirely loaded (IsoMapPack5 size limit)

### ISSUE THREAD

**Issue by Rampastring** [Vinifera-Developers/Vinifera#76]
### Description:
When big maps with high details cross about 9750 + few lines in the `[IsoMapPack5]` section, the game doesn't decode those remaining lines and fills the bottom-left corner of the map with height level 0 clear tiles.

### Steps To Reproduce:
Simply load a very a big map with lots of details and you'll notice the bottom-left corner of the map missing all of its detail, despite that the map is displayed correctly in the map editor (FinalSun).

### Additional Files:
The limit is extended by ts-patches: https://github.com/CnCNet/ts-patches/blob/master/src/isomappack5_limit_extend.asm
It's probably impossible to exceed the new limit with the maximum map size (256x256) that TS offers.

**Comment by CCHyper** [comment]
I wonder if it would be possible to dynamically set the buffer size based on the map dimensions?

**Comment by E1Elite** [comment]
Map dimension is not the exact one to one match with the number of lines in IsoMapPack5. A large map with less detail would have encoded better to get less lines than a similar map with high terrain detail.

**Comment by CCHyper** [comment]
> Map dimension is not the exact one to one match with the number of lines in IsoMapPack5. A large map with less detail would have encoded better to get less lines than a similar map with high terrain detail.

Good point, it should be safe for us to use the same approach as the patch linked then.

**Comment by E1Elite** [comment]
Yes, the patch only extends the artificial cap. The actual buffer usage depends on the size of IsoMapPack5 coming from the map. Already there are tools that give better compressed IsoMapPack5 for the same amount of map detail by sorting the tiles before encoding, but that is not done by FinalSun.

**Comment by CCHyper** [comment]
@E1Elite

Can you please attach a map that shows this issue so it can be observed in the unpatched Tiberian Sun?

**Comment by E1Elite** [comment]
For testing, these maps could be used which are made by Tuc0 at PPMForums.
* Divide And Conquer - https://ppmforums.com/topic-45126/ts-divide-and-conquer-2-8/
* Blood River - https://ppmforums.com/topic-47468/ts-blood-river-2-8/

Currently these maps have optimized IsoMapPack5 sections. To reproduce the problem, download the map, open it in FinalSun and save the map. File could be renamed to .mpr and placed in the game folder. Game loading could lag due to these additional files. On map launch look at bottom-left corner of the map where the IsoMapPack5 entries that were not processed by the game are filled with height level 0 clear tiles.

Blood river map needs editing the Map section in a text editor first to set the size from 214,228 to 204,214 so that FinalSun can open it.

**Comment by CCHyper** [comment]
@E1Elite 
> For testing, these maps could be used which are made by Tuc0 at PPMForums.
> 
>     * Divide And Conquer - https://ppmforums.com/topic-45126/ts-divide-and-conquer-2-8/
> 
>     * Blood River - https://ppmforums.com/topic-47468/ts-blood-river-2-8/
> 
> 
> Currently these maps have optimized IsoMapPack5 sections. To reproduce the problem, download the map, open it in FinalSun and save the map. File could be renamed to .mpr and placed in the game folder. Game loading could lag due to these additional files. On map launch look at bottom-left corner of the map where the IsoMapPack5 entries that were not processed by the game are filled with height level 0 clear tiles.
> 
> Blood river map needs editing the Map section in a text editor first to set the size from 214,228 to 204,214 so that FinalSun can open it.

Thanks for the map links. I resaved it using FinalSun and confirmed the issue on my end.

Resaved "Divide And Conquer" map for archiving purposes.
[divide_and_conquer_resaved.zip](https://github.com/Vinifera-Developers/Vinifera/files/6647741/divide_and_conquer_resaved.zip)
