### ISSUE TITLE
[Vinifera Bug] Coastal Path revisited (and potentially other Ant-inclusive maps too) error message and ant graphics issues in DTA mod. Have also opened a ticket on the mod's forums in case it's on their end, but no response so far.

### ISSUE THREAD

**Issue by Xenimme** [Vinifera-Developers/Vinifera#808]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, debug and exception logs, etc)*.

### Description

I keep getting the enclosed error, seemingly from Vinifera when playing Dawn of the Tiberian Age, and also ants that display the dead ant animation/graphics while still alive. I have supplied screenshots/images of both. As the title says, I am unsure if this is a vinifera issue, or a DTA issue, but I've posted on their forums in case too, but haven't received a response in a few days. The issues could be related, or maybe not, I'm unsure.

![Vinifera](https://user-images.githubusercontent.com/106463691/170855010-0028fd72-1246-40b0-9e46-70d204429b35.PNG)
![live ant](https://user-images.githubusercontent.com/106463691/170855158-245a8d94-e4fe-4f3f-adb8-a91ee91a0cac.PNG)
!

### Steps To Reproduce

Load up Dawn of the Tiberian Age 9.5.2
For the error, load up a skirmish with the Coastal Path Revisited map.
Receive error.

For the ant issue, several maps involving ants, including CPR and the ant missions.
As stated, It could be unrelated to the vinifera issue, which I full understand could be possible.

### Expected Behaviour

No error screen, and no buggy ants.

### Actual Behaviour

Error screen shows up, and ants look unusual.

### Version

Unsure, whichever DTA 9.5.2 uses.

### Additional Context

Any help would be greatly appreciated, as the DTA staff haven't gotten back to me in several days, so I'm unsure if their own support is even active or not.

Also apologies for if it is just a problem on their end instead, but some context/info on the error message itself would also be much appreciated.

**Comment by Rampastring** [comment]
Hey,

Please don't open DTA issue tickets on the Vinifera issue board, as Vinifera is a generic engine extension and not DTA-specific.

I've replied to your topic at PPM. We're most active on Discord as that's where the big majority of our fans are active and sometimes forget to visit the forums as they're relatively inactive. https://discord.gg/6UtC289
