### ISSUE TITLE
[New Feature] Box Selection Ignore Harvester

### ISSUE THREAD

**Issue by Onidotmoe** [Vinifera-Developers/Vinifera#825]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, videos, links, etc)*.

### Description

In C&C3 Harvesters are ignored when selecting units using box select and thereby not added to the selection, UNLESS there's only Harvesters inside the box selection.

This would be a nice option to have.

**Comment by Metadorius** [comment]
Related YR implementation: https://github.com/Phobos-developers/Phobos/blob/develop/src/Misc/Selection.cpp
