### ISSUE TITLE
[New Feature] Use Box Select to Add to Selection

### ISSUE THREAD

**Issue by Onidotmoe** [Vinifera-Developers/Vinifera#848]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, videos, links, etc)*.

### Description

In C&C3 if you have a existing selection you can add to it with box select, in Tiberian Sun you can't do that and have to click on each unit individually to add them to the current selection.

**Comment by ZivDero** [comment]
Can already be done using `Shift`
