### ISSUE TITLE
[Vinifera Bug] Ice growth toggles do not work

### ISSUE THREAD

**Issue by Crimsonum** [Vinifera-Developers/Vinifera#861]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, debug and exception logs, etc)*.

### Description

There appears to be two intended ways to toggle ice growth in a map.
1. Global map setting:
```ini
[Basic]
IceGrowthEnabled=yes
```
2. Trigger action `87`

However, neither of them work. The only way to modify ice growth is to toggle it per each ice tile in the map's `IsoMapPack5`. Unfortunately, no editor can conveniently edit this property per tile.

### Steps To Reproduce

In a snow map with ice, try disabling ice growth via `[Basic]` -> `IceGrowthEnabled=no` or via the trigger action `87`.

### Expected Behaviour

Ice growth should be disabled for the map.

### Actual Behaviour

Ice growth depends entirely on data encoded in `IsoMapPack5`. Neither toggle has any effect.

**Comment by CCHyper** [comment]
Changing the label and name of this issue to be a Vinifera bug, as it seems to have been introduced with the custom TheaterTypes feature.
