### ISSUE TITLE
[Vanilla Bug] Civilians can't own walls when when another house owns any pre-placed structure on a map

### ISSUE THREAD

**Issue by Bittah** [Vinifera-Developers/Vinifera#914]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, debug and exception logs, etc)*.

### Description

When there are civilian outposts with walls and armed units or structures on a map, these units/structures will attack those walls when the map is loaded if there's any pre-placed structure on the map that's owned by a house other than Neutral or Special.

### Steps To Reproduce

[walls.zip](https://github.com/Vinifera-Developers/Vinifera/files/10042922/walls.zip)
Place the included map file in the TS Client's `\Maps\Custom\` folder and start a match on it with the TS Client.

Note: This can only be re-produced with the TS Client because pre-placed structures belonging to playable multiplayer houses (GDI/Nod) are removed from the map when the map is loaded, which means that the pre-placed structures need to be owned by one of the Spawn# houses that are added by ts-patches in order to remain on the map when it's loaded.

### Expected Behaviour

The walls will be owned by the Civilians in the center and the defensive structures and units will remain idle until an enemy approaches.

### Actual Behaviour

The walls are actually owned by whichever player (Spawn1) owns the pre-placed Nod Pyramid in the upper left corner of the map (the same player is able to also sell the walls) and the defensive structures and units in the center of the map start attacking the walls as soon as the map is loaded.

### Additional Context

On the included test map there is a "Nod Pyramid" placed all the way in the top-left corner, which is owned by Spawn1 (meaning that it'll belong to whichever player starts at waypoint 0). The player that ends up owning this Nod Pyramid will also own the walls in the center of the map and will be able to sell them, which is why the civilian units surrounding it are attacking it.
![Untitled-1](https://user-images.githubusercontent.com/7165430/202750766-29bea744-ef58-4051-ba30-012a9d82adf9.png)
There is also a Nod Pyramid owned by the Neutral house in the center of the map to make clear an identical Neutral-owned structure that's much closer to the walls doesn't overrule the Spawn1-owned structure that's tucked away in the upper left corner of the map.
Removing the Nod Pyramid from the map's upper left corner or changing its house to Neutral will prevent the neutral units/structures from attacking the walls.

Additional example in DTA:
![dawn_of_the_tiberium_age-2022-11-18-15_48_10](https://user-images.githubusercontent.com/7165430/202752948-86f071b3-4e9d-45e7-8099-07562dd32602.png)

**Comment by ZivDero** [comment]
Not a vanilla bug but a bug with the TS-Patches implementation of spawn houses, not present in vanilla/Vinifera
