### ISSUE TITLE
[New Feature] Support loading the games CD files locally.

### ISSUE THREAD

**Issue by CCHyper** [Vinifera-Developers/Vinifera#94]
### Description:
Support loading the game's CD files locally if detected. This should not be implemented with a "no-cd" approach, as this does not take into consideration that the game expects certain files to be available depending on the `CD=` entry for campaigns in `BATTLE.INI`.

Supporting this would also allow other releases of Tiberian Sun (The First Decade for example) to work without much user intervention. It would also allow mods to strip back the game files and leave the bare minimum available without the game reporting an error.

### Possible Implementation:
The following could be implemented;

- Add the CD/volume name directories `TS1`, `TS2`, `FIRESTORM` to the games search paths.
- Introduce the `-CD` command-line argument which previous games had.
- Extend the games CD swapping mechanic to load files based on the `CD=` in `BATTLE.INI` entries.

**Comment by Rampastring** [comment]
I decided to close my issue as I noticed this, but it's closely related: https://github.com/Vinifera-Developers/Vinifera/issues/108

**Comment by CCHyper** [comment]
The feature was merged early on as part of TS Client support.
