### ISSUE TITLE
[New Feature] Remove the requirement for BLOWFISH.DLL (Blowfish encryption).

### ISSUE THREAD

**Issue by CCHyper** [Vinifera-Developers/Vinifera#96]
### Description:
Tiberian Sun uses BLOWFISH.DLL (the Blowfish algorithm) to handle encrypted MIX files. This system uses Microsoft COM, and mods that use the Freeware TS installation as a base do not create the required registry entries for this to work correctly. As a result, some end users have issues playing these mods without receiving technical help. 

### Possible Implementation:
The only possible implementation for this is to embed the BlowfishEngine into the Vinifera DLL directly and patch all existing code to use it.

Implementing this embedded into the DLL would remove a common issue most mods and players on modern systems experience.

**Comment by Rampastring** [comment]
AFAIK pretty much all current TS mods use this patch to skip loading BLOWFISH.DLL and simply don't use encrypted MIX files: https://github.com/CnCNet/ts-patches/blob/master/src/no_blowfish_dll.asm

Would still be better to implement the Blowfish Engine in the DLL of course, but just saying that it's not a priority / issue for mods right now.
