### ISSUE TITLE
[Vinifera Bug] New SearchPaths don't work

### ISSUE THREAD

**Issue by Bittah** [Vinifera-Developers/Vinifera#963]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, debug and exception logs, etc)*.

### Description

Adding new paths to `SearchPaths = ` in Vinifera.ini doesn't have any effect.

### Required Code (optional)

```ini
SearchPaths = ZINI,INI,MIX,SOUNDS,MUSIC,MOVIES,MAPS
```

### Steps To Reproduce

- Add `SearchPaths = ZINI,INI,MIX,SOUNDS,MUSIC,MOVIES,MAPS` to Vinifera.ini
- Copy the INI folder and name the copy `ZINI`
- Delete Rules.ini from the `INI` folder so that it only exists in ZINI

### Expected Behaviour

The game launches as usual.

### Actual Behaviour

The game crashes while loading a map.

### Version

~fa8333c

### Additional Context

Attempting the same thing with a different INI file such as Firestrm.ini also results in the game not finding the file.
Replacing or removing `INI` from `SearchPaths = ` has no effect (the game still loads fine if the INI folder exists).

**Comment by CCHyper** [comment]
This has been fixed upstream, closing the issue.
